[tool.pytest.ini_options]
testpaths = ["tests"]
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(levelname).1s %(name)s: %(message)s"
log_cli_date_format = "%H:%M:%S"
log_file_level = "INFO"
log_file_format = "%(levelname).1s %(name)s: %(message)s"
log_file_date_format = "%H:%M:%S"
